import { fileURLToPath } from "url";

import { ServiceLocator } from "@vertix.gg/base/src/modules/service/service-locator";

import { UIModuleBase } from "@vertix.gg/gui/src/bases/ui-module-base";
import { UICustomIdHashStrategy } from "@vertix.gg/gui/src/ui-custom-id-strategies/ui-custom-id-hash-strategy";

import { DynamicChannelPrimaryMessageElementsGroup } from "@vertix.gg/bot/src/ui/v3/dynamic-channel/primary-message/dynamic-channel-primary-message-elements-group";

import { DynamicChannelFlow } from "@vertix.gg/bot/src/ui/general/flows/dynamic-channel-flow";
import { DynamicChannelClaimManager } from "@vertix.gg/bot/src/managers/dynamic-channel-claim-manager";

import * as adapters from "@vertix.gg/bot/src/ui/v3/ui-adapters-index";

import type { UIService } from "@vertix.gg/gui/src/ui-service";
import type { TAdapterClassType } from "@vertix.gg/gui/src/definitions/ui-adapter-declaration";

const adapterClasses: Record<string, TAdapterClassType> = adapters;

export class UIModuleV3 extends UIModuleBase {
    public static getName() {
        return "VertixBot/UI-V3/Module";
    }

    public static getSourcePath() {
        return fileURLToPath( import.meta.url );
    }

    public static getAdapters(): ReadonlyArray<TAdapterClassType> {
        return Object.values( adapterClasses );
    }

    /**
     * UI flows are now generated from adapter transactions.
     * Virtual flows are auto-generated by the UIDefinitionExporter from
     * adapters that use `defineTransactions()`.
     */
    public static getFlows() {
        return [];
    }

    public static override getSystemFlows() {
        return [
            DynamicChannelFlow
        ];
    }

    public get $$() {
        return this.constructor as typeof UIModuleV3;
    }

    protected getCustomIdStrategy() {
        return new UICustomIdHashStrategy();
    }

    protected async initialize() {
        // Skip DynamicChannelClaimManager registration in headless mode (no bot services available)
        const dynamicChannelService = ServiceLocator.$.get( "VertixBot/Services/DynamicChannel", { silent: true } );
        if ( !dynamicChannelService ) {
            return;
        }

        const uiService = ServiceLocator.$.get<UIService>( "VertixGUI/UIService" );

        DynamicChannelClaimManager.register( "VertixBot/UI-V3/DynamicChannelClaimManager", {
            adapters: {
                claimStartAdapter: () => uiService.get( adapters.ClaimStartAdapter.getName() )!,
                claimVoteAdapter: () => uiService.get<"execution">( adapters.ClaimVoteAdapter.getName() )!,
                claimResultAdapter: () => uiService.get<"execution">( adapters.ClaimResultAdapter.getName() )!
            },

            dynamicChannelClaimButtonId: DynamicChannelPrimaryMessageElementsGroup.getByName(
                "VertixBot/UI-V3/DynamicChannelClaimChannelButton"
            )!.getId()
        } );
    }
}

export default UIModuleV3;
