export const VERTIX_DEFAULT_COLOR_BRAND = 0x336beb,
    VERTIX_DEFAULT_COLOR_YELLOW = 0xffd700,
    VERTIX_DEFAULT_COLOR_ORANGE_RED = 0xff6900;

export const VERTIX_PROTECTED_ID = "1071097917743583384";

export const VERTIX_DEFAULT_SURVEY_COLLECTOR_ID = VERTIX_PROTECTED_ID;

export const VERTIX_OWNERS_IDS = [VERTIX_PROTECTED_ID];
