export const VERSION_PHASE_4_ARCHIVE_RECORD = "0.0.1",
    VERSION_PHASE_5_ARCHIVE_RECORD = "0.0.2",
    VERSION_PHASE_6 = "0.0.1",
    VERSION_PHASE_6_1 = "0.0.2",
    VERSION_PHASE_6_2 = "0.0.3",
    VERSION_WITH_TRANSFER_DYNAMIC_CHANNELS = "0.0.4",
    CURRENT_VERSION = VERSION_WITH_TRANSFER_DYNAMIC_CHANNELS
;
