export const DEFAULT_GUILD_SETTINGS_KEY_BADWORDS = "badwords",
    DEFAULT_GUILD_SETTINGS_KEY_LANGUAGE = "language",
    DEFAULT_GUILD_SETTINGS_KEY_STAFF_ROLES = "staffRoles",
    DEFAULT_GUILD_SETTINGS_KEY_TIMINGS = "timings",
    DEFAULT_GUILD_SETTINGS_KEY_VERIFIED_ROLES = "verifiedRoles",
    DEFAULT_GUILD_SETTINGS_KEY_VOICE_ROLE = "voiceRole";
