export const GUILD_DEFAULT_BADWORDS = [],
    GUILD_DEFAULT_BADWORDS_INITIAL_VALUE = "",
    GUILD_DEFAULT_BADWORDS_INITIAL_DISPLAY_VALUE = "None",
    GUILD_DEFAULT_BADWORDS_PLACEHOLDER = "None",
    GUILD_DEFAULT_BADWORDS_SEPARATOR = ", ";
