permissions:
  # All other permissions are set to none
  checks: write
  contents: read
  pull-requests: write

name: Jest

on: [ push, pull_request ]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  file-diff:
    runs-on: ubuntu-20.04
    name: File Diff
    outputs:
      js_diff: ${{ steps.js_diff_files.outputs.diff }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Check JS files diff
        id: js_diff_files
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.+(js|ts|json|jsx|tsx)
            package*.json
            .github/**/*.yml
  jest:
    runs-on: ubuntu-20.04
    needs: [ 'file-diff' ]
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run vertix:ci:jest
